# Default values for rollouts-demo.

replicaCount: 5

image:
  repository: argoproj/rollouts-demo
  pullPolicy: IfNotPresent
  tag: blue

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80


# gateway.networking.k8s.io/v1alpha2 Gateway configuration
# defaults for Traefik controller
gateway:
  enabled: true
  className: traefik
  annotations: {}
  port:
    web: 8000
    websecure: 8443
  host: ""
  target: ""
  matches:
    canary: []
      # - name: version
      #   value: 2

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 5m
    memory: 32Mi
