{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: {{ include "rollouts-demo.fullname" . }}
  labels:
    {{- include "rollouts-demo.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      hostname: {{ .Values.gateway.host }}
      protocol: HTTP
      port:  {{ .Values.gateway.port.web }}
    - name: https
      hostname: {{ .Values.gateway.host }}
      protocol: HTTPS
      port: {{ .Values.gateway.port.websecure }}
      tls:
        certificateRefs:
          - name: {{ include "rollouts-demo.fullname" . }}-tls
{{- end }}