{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: {{ include "rollouts-demo.fullname" . }}
  annotations:
    config.kubernetes.io/depends-on: /namespaces/{{ .Release.Namespace }}/Service/{{ include "rollouts-demo.fullname" . }},/namespaces/{{ .Release.Namespace }}/Service/{{ include "rollouts-demo.fullname" . }}-stable,/namespaces/{{ .Release.Namespace }}/Service/{{ include "rollouts-demo.fullname" . }}-canary
spec:
  hostnames:
    - {{ .Values.gateway.host }}
  parentRefs:
    - name: {{ include "rollouts-demo.fullname" . }}
  rules:
    - backendRefs:
        - name: {{ include "rollouts-demo.fullname" . }}-canary
          port: {{ .Values.service.port }}
      matches:
        - headers:
          {{- toYaml .Values.gateway.matches.canary | nindent 10 }}
    - backendRefs:
        - name: {{ include "rollouts-demo.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
