apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollouts-demo.fullname" . }}
  labels:
    {{- include "rollouts-demo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rollouts-demo.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollouts-demo.fullname" . }}-canary
  labels:
    {{- include "rollouts-demo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollouts-demo.fullname" . }}-stable
  labels:
    {{- include "rollouts-demo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
